### ISSUE TITLE
no save to node and cancle option

### ISSUE THREAD

**Issue by yamanacn** [coolzilj/ComfyUI-Photopea#3] opened 2024-05-31 08:26 UTC
![1717143949973](https://github.com/coolzilj/ComfyUI-Photopea/assets/74345043/ee2cdcab-454a-4336-8754-d90f9ea2e777)

**Comment by coolzilj** [comment] 2024-05-31 08:42
seems like a UI issue, did you use other extensions to modify theme?

**Comment by laitianwen** [comment] 2024-06-01 01:40
How did you solve the same problem?

**Comment by coolzilj** [comment] 2024-06-02 14:36
I'm closing because you haven't responded. Please open another ticket if your issue remains unresolved.

**Closed by coolzilj** 2024-06-02 14:36 UTC

**Comment by laitianwen** [comment] 2024-06-02 14:42
Or is it the same problem? I don't have any other UI themes.



------------------ Original ------------------
From: Jin Liu ***@***.***&gt;
Date: Sun,Jun 2,2024 10:37 PM
To: coolzilj/ComfyUI-Photopea ***@***.***&gt;
Cc: laitianwen ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [coolzilj/ComfyUI-Photopea] no save to node and cancle option(Issue #3)





 
I'm closing because you haven't responded. Please open another ticket if your issue remains unresolved.

**Comment by coolzilj** [comment] 2024-06-02 15:04
> Or is it the same problem? I don't have any other UI themes.
> […](#)
> ------------------ Original ------------------ From: Jin Liu ***@***.***&gt; Date: Sun,Jun 2,2024 10:37 PM To: coolzilj/ComfyUI-Photopea ***@***.***&gt; Cc: laitianwen ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [coolzilj/ComfyUI-Photopea] no save to node and cancle option(Issue #3) I'm closing because you haven't responded. Please open another ticket if your issue remains unresolved. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Just push a new version to prevent conflicts in case other extensions globally overwrite iframe styles. 
This update fixes issues caused by custom nodes like AIGODLIKE-ComfyUI-Studio. 
You should update to the latest version to check if your problem is resolved.
